#! /bin/bash

coqdep -Q . SystemFR *.v |
  sed '/^[^.]*.vio/d' |
  sed 's/\.vo//g' |
  sed 's/[A-Za-z0-9]\+\.\(glob\|v\.beautified\|required_vo\|v\)//g' |
  makefile2dot.py > dependencies_temp.dot

tred dependencies_temp.dot > dependencies.dot

dot -T pdf dependencies.dot > dependencies.pdf

rm dependencies.dot dependencies_temp.dot
