#! /bin/bash

coqdep -Q . SystemFR -dumpgraph dependencies.dot *.v

finished=0
total=0

for f in *.vo
do
  base=$(basename "$f" .vo)
  v="$base.v"
  echo "Checking $base"
  total=$((total+1))
  if $(make -q $f)
  then
    finished=$((finished+1))
    sed -i s/=\"$base\"/=\"$base\",fillcolor=lightgreen,style=filled/g dependencies.dot
  fi
done

dot -T pdf dependencies.dot > dependencies.pdf

rm dependencies.dot

echo "Finished: $finished"
echo "Total: $total"
