#! /bin/bash

coqdep -Q . SystemFR -dumpgraph dependencies.dot *.v

finished=0
total=0

for v in *.v
do
  base=$(basename "$v" .v)
  vo="$base.vo"
  echo "Checking $base"
  total=$((total+1))
  if $(make -q $vo)
  then
    finished=$((finished+1))
    sed -i s/=\"$base\"/=\"$base\",fillcolor=lightgreen,style=filled/g dependencies.dot
  fi
done

dot -T pdf dependencies.dot > dependencies.pdf

rm dependencies.dot

echo "Finished: $finished"
echo "Total: $total"
