#! /bin/bash

rocq dep -Q . SystemFR *.v |
  sed '/^[^.]*.vio/d' |
  sed 's/\.vo//g' |
  sed 's/[A-Za-z0-9]\+\.\(glob\|v\.beautified\|required_vo\|v\)//g' |
  makefile2dot.py > dependencies_temp.dot

tred dependencies_temp.dot > dependencies.dot

sed -i '$ d' dependencies.dot

finished=0
total=0

for v in *.v
do
  base=$(basename "$v" .v)
  vo="$base.vo"
  echo "Checking $base"
  total=$((total+1))
  if $(make -q $vo)
  then
    finished=$((finished+1))
    echo "$base [style=filled, fillcolor=lightgreen];" >> dependencies.dot
  else
    echo "$base [style=filled, fillcolor=lightcoral];" >> dependencies.dot
  fi
done

echo "}" >> dependencies.dot

dot -T pdf dependencies.dot > dependencies.pdf

rm dependencies.dot dependencies_temp.dot

echo "Finished: $finished"
echo "Total: $total"
