name: Build

on:
  push:
    branches: [master]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        tags: systemfr
        cache-from: type=gha
        cache-to: type=gha,mode=max
        load: true

    - name: Build SystemFR
      run: docker run --rm -v "$(pwd)":/theories systemfr
